[package]
name = "command"
version = "0.1.0"
edition = "2024"

[dependencies]
pumpkin = { git = "https://github.com/Pumpkin-MC/Pumpkin" }
pumpkin-api-macros = { git = "https://github.com/Pumpkin-MC/Pumpkin" }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tokio = "1"

[lib] 
crate-type = ["cdylib"]

[profile.release] 
lto = true
